### ISSUE TITLE
Subtitle truncation not quite right

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/autocat3#110]
The production team reported that truncation on the landing page doesn't seem quite right.

See: https://gutenberg.org/ebooks/71695

Truncation at the top of the landing page is "a", which seems incorrect.
The full subtitle is part of the bibrec & database. This is correct.
Truncation within the HTML & text is "China." This seems better than what's at the top of the landing page.

**Comment by eshellman** [comment]
Strings in this element are truncated at word breaks so that the length is <80 character. There are several titles in the db over 300 characters long.

One mitigation might be to add `…` after truncated strings. A bit tricky given the other uses of the truncated title.

We could also use the full title and use css to allow the title to overflow the element's bounding box. This would be much cleaner, but could have unexpected rendering consequences for long titles.

A simple partial mitigation that would work for this book, and those that have been processed after ~ the beginning of 2023 is to use `title_no_subtitle` instead of a truncated title. This would look terrible for the older long titles in the backlist, and would probably be called out as an error when the title without subtitle is a single short word. 

One more option is to modify the truncation algorithm to not widow single letter words  or punctuation at the end of a truncated title.

My preference is either the css mitigation (though working with css is painful) or the single-letter word anti-widowing mitigation.

"won't fix" is also an option 😄

**Comment by eshellman** [comment]
I don't really have a preference.

**Comment by gbnewby** [comment]
My preference is single-letter word anti-widowing, perhaps with a little
additional intelligence:

- drop single-letter words
- also a drop-list of other two or three-letter words: but, and, for, of,
in, an, as, at, by, on, to. (maybe you can think of a few more)
- don't allow just one word after punctuation. Instead, truncate the
punctuation & onward

I think this approach will make the displayed title look less like an error.

I would have liked to include "..." when truncation happens, but understand
why that might be more challenging.

**Comment by eshellman** [comment]
I think if we use '...' (3 dots) instead of '…' my concerns go away, and I'd rather do that that deal with drop words - someone's always going to complain. Also, punctuation is too complicated to get right.

**Comment by gbnewby** [comment]
Yes, I agree.

**Comment by gbnewby** [comment]
This looks complete, to me. Truncation is much better. Unless there is further ongoing work, this issue can be closed.

**Comment by eshellman** [comment]
not deployed on production yet

**Comment by eshellman** [comment]
done in #117, and deployed Jan 12
