### ISSUE TITLE
Incomplete search results on advanced search screen

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/autocat3#120]
Based on some email correspondence & clarification, the root cause may be an incomplete deletion or other inconsistency or problem in the catalog database.

To demonstrate the problem: There are three books by the same author. The most recent two were posted at the end of January.

The three books are correctly linked to the author:
https://www.gutenberg.org/ebooks/author/56829

Here they are:
https://www.gutenberg.org/ebooks/54449
https://www.gutenberg.org/ebooks/72833
https://www.gutenberg.org/ebooks/72841 <-- doesn't show up in advanced search

In the Advanced Search pane on https://www.gutenberg.org/ebooks, enter:

Author: topelius
Title: vanhoja

...and the message is "3 books found" but **only the first two are listed.**

This doesn't seem to be a general problem impacting all advanced search results. I tried author=shakespeare and title=nothing, and was correctly presented with 11 books (including one audiobook).

**Comment by eshellman** [comment]
This problem must be fixed in the catalog interface.

in the edit book page, (https://gutenberg.org/catalog/admin/book?mode=edit&fk_books=72841) the link to the author is displayed as :
![image](https://github.com/gutenbergtools/autocat3/assets/926513/1781325b-bdf6-4258-9f54-b97e97d92801)
Note the entry "No Heading".
Click on "Edit Link", (https://gutenberg.org/catalog/admin/mn_books_authors?fk_books=72841&mode=edit&fk_authors=56829&fk_roles=com) then select "Heading"
![image](https://github.com/gutenbergtools/autocat3/assets/926513/d522f539-00cc-4da2-a7ba-3b3c62866c9c)
and save.
The No Heading value is used to suppress display of duplicate results when a search retrieves both an author name and an alias name - the correct entry should have "Heading", while the alias should have "No Heading". 
In the present issue, the "No Heading" was set on initial load. When the author link was changed, the "No Heading" remained on the author - book link record.

I don't believe it is practical to change this in the catalog interface, other than to add to the workflow documentation.

I have made the change in the prod db to verify that this fixes the current issue.

**Comment by gbnewby** [comment]
Thanks for this this.

Can you clarify whether the "no heading" was a bug that was now fixed?

Or, did a human cataloger accidentally set "no heading?"
  ~ Greg

**Comment by eshellman** [comment]
I believe that the "No Heading" setting came about because there were two authors with the same name, and correcting the author assignment was a side effect of correcting the assignment of the book to the wrong author. I do not find it obvious what the "No Heading" label means in the cataloguing context, but I doubt that the workflow of correcting an incorrect author assignment in the context of duplicate author names would give any hint that the heading value needs to be checked.
